//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Houses
    {
        public int HouseId { get; set; }
        public string HouseTitle { get; set; }
        public Nullable<byte> HouseType { get; set; }
        public string HouseZone { get; set; }
        public string HouseAddress { get; set; }
        public string HouseDescription { get; set; }
        public string HouseFirstPicture { get; set; }
        public string HouseSecondPicture { get; set; }
        public string HouseThirdPicture { get; set; }
        public string HouseForthPicture { get; set; }
        public Nullable<int> HouseMortgage { get; set; }
        public Nullable<int> HouseRentPrice { get; set; }
        public string HousePhoneNumber { get; set; }
        public Nullable<System.DateTime> HouseRegisteredDate { get; set; }
        public Nullable<int> HouseVisitedCount { get; set; }
        public string HouseBenefits { get; set; }
        public string HouseLatitiud { get; set; }
        public string HouseLongitiud { get; set; }
        public Nullable<byte> HouseGender { get; set; }
        public Nullable<int> HouseSingleBed { get; set; }
        public Nullable<int> HouseDoubleBed { get; set; }
        public Nullable<int> HouseTripleBed { get; set; }
        public Nullable<int> HouseBedOfFour { get; set; }
        public Nullable<int> HouseBedOfSix { get; set; }
        public Nullable<int> HouseBedOfEight { get; set; }
        public Nullable<int> HouseBedOfTen { get; set; }
        public Nullable<int> HouseOwnerId { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
