//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Users()
        {
            this.T_Houses = new HashSet<T_Houses>();
        }
    
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserMobileNumber { get; set; }
        public Nullable<int> UserStateCode { get; set; }
        public Nullable<int> UserCityCode { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string Description { get; set; }
        public string UserPassword { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Houses> T_Houses { get; set; }
    }
}
